
package com.rapidclipse.demo.globalactions.ui;

import java.beans.Beans;

import com.flowingcode.vaadin.addons.ironicons.IronIcons;
import com.rapidclipse.demo.globalactions.ui.actions.SaveAction;
import com.rapidclipse.framework.server.ui.action.ActionRegistry;
import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.orderedlayout.HorizontalLayout;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.router.RouterLayout;
import com.vaadin.flow.router.RouterLink;
import com.vaadin.flow.server.InitialPageSettings;
import com.vaadin.flow.server.PageConfigurator;
import com.vaadin.flow.server.VaadinService;


/**
 *
 */
public class MainLayout extends VerticalLayout implements PageConfigurator, RouterLayout
{
	/**
	 *
	 */
	public MainLayout()
	{
		super();
		this.initUI();
	}

	@Override
	public void configurePage(final InitialPageSettings settings)
	{
		settings.addLink("shortcut icon", "frontend/images/favicon.ico");
		settings.addFavIcon("icon", "frontend/images/favicon256.png", "256x256");
	}

	/* WARNING: Do NOT edit!<br>The content of this method is always regenerated by the UI designer. */
	// <generated-code name="initUI">
	private void initUI()
	{
		this.horizontalLayout = new HorizontalLayout();
		this.routerLink       = new RouterLink();
		this.routerLink2      = new RouterLink();
		this.routerLink3      = new RouterLink();
		this.cmdSave          = new Button();

		this.routerLink.setText("View1");
		if(!Beans.isDesignTime())
		{
			this.routerLink.setRoute(VaadinService.getCurrent().getRouter(), View1.class);
		}
		this.routerLink2.setText("View2");
		if(!Beans.isDesignTime())
		{
			this.routerLink2.setRoute(VaadinService.getCurrent().getRouter(), View2.class);
		}
		this.routerLink3.setText("View3");
		if(!Beans.isDesignTime())
		{
			this.routerLink3.setRoute(VaadinService.getCurrent().getRouter(), View3.class);
		}
		this.cmdSave.setText("Save");
		ActionRegistry.connect(this.cmdSave, SaveAction.class);
		this.cmdSave.setIcon(IronIcons.SAVE.create());

		this.cmdSave.setSizeUndefined();
		this.horizontalLayout.add(this.routerLink, this.routerLink2, this.routerLink3, this.cmdSave);
		this.horizontalLayout.setSizeUndefined();
		this.add(this.horizontalLayout);
		this.setSizeFull();
	} // </generated-code>
	
	// <generated-code name="variables">
	private Button           cmdSave;
	private HorizontalLayout horizontalLayout;
	private RouterLink       routerLink, routerLink2, routerLink3;
	// </generated-code>

}
