
package com.rapidclipse.demo.globalactions.ui;

import com.vaadin.flow.component.html.Label;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.router.ParentLayout;
import com.vaadin.flow.router.Route;


@ParentLayout(MainLayout.class)
@Route(value = "view2", layout = MainLayout.class)
public class View2 extends VerticalLayout
{
	
	/**
	 *
	 */
	public View2()
	{
		super();
		this.initUI();
	}
	
	/* WARNING: Do NOT edit!<br>The content of this method is always regenerated by the UI designer. */
	// <generated-code name="initUI">
	private void initUI()
	{
		this.label = new Label();
		
		this.label.setText("This view is not saveable");
		
		this.label.setSizeUndefined();
		this.add(this.label);
		this.setSizeFull();
	} // </generated-code>
	
	// <generated-code name="variables">
	private Label label;
	// </generated-code>
	
}
