
package com.rapidclipse.demo.globalactions.ui;

import com.rapidclipse.demo.globalactions.ui.actions.Saveable;
import com.vaadin.flow.component.html.Label;
import com.vaadin.flow.component.notification.Notification;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.router.ParentLayout;
import com.vaadin.flow.router.Route;


@ParentLayout(MainLayout.class)
@Route(value = "view3", layout = MainLayout.class)
public class View3 extends VerticalLayout implements Saveable
{
	
	/**
	 *
	 */
	public View3()
	{
		super();
		this.initUI();
	}

	@Override
	public void save()
	{
		Notification.show("Saved");
	}
	
	/* WARNING: Do NOT edit!<br>The content of this method is always regenerated by the UI designer. */
	// <generated-code name="initUI">
	private void initUI()
	{
		this.label = new Label();
		
		this.label.setText("This view is also saveable");
		
		this.label.setSizeUndefined();
		this.add(this.label);
		this.setSizeFull();
	} // </generated-code>
	
	// <generated-code name="variables">
	private Label label;
	// </generated-code>
	
}
